In [1]:
import numpy as np

La concaténation et le fractionnement de tableaux NumPy sont deux opérations importantes et opposées sur les tableaux.

La concaténation de tableaux consiste à joindre plusieurs tableaux. Horizontalement ou verticalement.

Le fractionnement de tableaux consiste à diviser l'unique tableau. Les éléments du tableau sont divisés en utilisant leurs indices.

# **Contaténation**

In [4]:
a1 = np.arange(1, 5)
a2 = np.arange(5, 9)
a1 , a2

(array([1, 2, 3, 4]), array([5, 6, 7, 8]))

In [5]:
np.concatenate([a1 , a2])

array([1, 2, 3, 4, 5, 6, 7, 8])

## _Concaténer deux tableaux 2d_

In [7]:
a3 = np.arange(1, 10).reshape(3, 3)
a4 = np.arange(10, 19).reshape(3, 3)
a3 , a4

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]))

In [8]:
np.concatenate([a3, a4])

array([[ 1, 2, 3],
 [ 4, 5, 6],
 [ 7, 8, 9],
 [10, 11, 12],
 [13, 14, 15],
 [16, 17, 18]])

## _Concaténation verticale_

In [10]:
np.concatenate([a3, a4], axis=1)

array([[ 1, 2, 3, 10, 11, 12],
 [ 4, 5, 6, 13, 14, 15],
 [ 7, 8, 9, 16, 17, 18]])

Jointure verticale `vstack()`.  
Jointure horizontalement `hstack()`.

In [12]:
np.vstack([a3, a4])

array([[ 1, 2, 3],
 [ 4, 5, 6],
 [ 7, 8, 9],
 [10, 11, 12],
 [13, 14, 15],
 [16, 17, 18]])

In [13]:
np.hstack([a3, a4])

array([[ 1, 2, 3, 10, 11, 12],
 [ 4, 5, 6, 13, 14, 15],
 [ 7, 8, 9, 16, 17, 18]])

# **Fractionnement**

In [15]:
a5 = np.arange(1, 10)
a5

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.split(a5, [4]) # fraction à l'index 4, donc le 5

[array([1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [17]:
np.split(a5, [3, 5, 7]) # le couper en 4

[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

## _Fractionner un tableau 2d_

In [19]:
a6 = np.arange(1, 21).reshape(5, 4)
a6

array([[ 1, 2, 3, 4],
 [ 5, 6, 7, 8],
 [ 9, 10, 11, 12],
 [13, 14, 15, 16],
 [17, 18, 19, 20]])

In [20]:
np.split(a6, [2])

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20]])]

In [21]:
np.split(a6, [2], axis=1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16],
        [19, 20]])]

In [22]:
np.vsplit(a6, [3])

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16],
        [17, 18, 19, 20]])]

In [23]:
np.hsplit(a6, [2])

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16],
        [19, 20]])]

In [24]:
np.hsplit(a6, [2])

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16],
        [19, 20]])]

## Fractionner et diviser un tableau en forme (6,5)

In [26]:
a = np.arange(30).reshape(6, 5)
a

array([[ 0, 1, 2, 3, 4],
 [ 5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14],
 [15, 16, 17, 18, 19],
 [20, 21, 22, 23, 24],
 [25, 26, 27, 28, 29]])

### _Fractionnement vertical `vsplit()`_

In [28]:
vsplit_arrays = np.vsplit(a, 2)
for part in vsplit_arrays:
    print(part)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


### _Fractionnement horizontal `hsplit()`_

In [30]:
hsplit_arrays = np.hsplit(a, 5)
for part in hsplit_arrays:
    print(part)

[[ 0]
 [ 5]
 [10]
 [15]
 [20]
 [25]]
[[ 1]
 [ 6]
 [11]
 [16]
 [21]
 [26]]
[[ 2]
 [ 7]
 [12]
 [17]
 [22]
 [27]]
[[ 3]
 [ 8]
 [13]
 [18]
 [23]
 [28]]
[[ 4]
 [ 9]
 [14]
 [19]
 [24]
 [29]]
