In [1]:
import numpy as np

In [2]:
arr = np.arange(1, 11)
arr

array([ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# **Fonctions universelles NumPy `Ufuncs`**

Les `Ufuncs` de NumPy rendent plus efficaces les opérations sur les tableaux.

Les `Ufuncs` de trois opérations majeures :
* Opérations arithmétiques
* Opérations d’agrégation
* Opérations de comparaison

# **Opérations arithmétiques**
* `add()`
* `substract()`
* `multiply()`
* `divide()`
* `floor_divide()`
* `power()`
* `mod()`

In [6]:
np.add(arr, 5) # Ajouter 5 éléments

array([ 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])

In [7]:
np.subtract(arr, 2) # Enlève en 2

array([-1, 0, 1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
np.multiply(arr, 10)

array([ 10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

In [9]:
np.divide(arr, 100)

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ])

In [10]:
np.floor_divide(arr, 4)

array([0, 0, 0, 1, 1, 1, 1, 2, 2, 2])

In [11]:
np.power(arr, 2)

array([ 1, 4, 9, 16, 25, 36, 49, 64, 81, 100])

In [12]:
np.mod(arr, 2)

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

# **Opérations d’agrégation**
* `moyenne()`
* `médiane()`
* `std()`
* `var()`
* `min()`
* `max()`

In [14]:
arr1 = np.array([1, 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

In [15]:
np.mean(arr1)

3.0

In [16]:
np.median(arr1)

3.0

In [17]:
np.std(arr1)

1.4142135623730951

In [18]:
np.var(arr1)

2.0

In [19]:
np.min(arr1)

1

In [20]:
np.max(arr1)

5

# **Opérations de comparaison**
* `equal()`
* `less()`
* `less_equal()`
* `greater()`
* `greater_equal()`
* `not_equal()`

In [22]:
a1 = np.array([1, 2, 3, 4])
a2 = np.array([1, 0, 3, 7])
a1, a2

(array([1, 2, 3, 4]), array([1, 0, 3, 7]))

In [23]:
np.equal(a1, a2)

array([ True, False, True, False])

In [24]:
np.less(a1, a2)

array([False, False, False, True])

In [25]:
np.less_equal(a1, a2)

array([ True, False, True, True])

In [26]:
np.greater(a1, a2)

array([False, True, False, False])

In [27]:
np.greater_equal(a1, a2)

array([ True, True, True, False])

In [28]:
np.not_equal(a1, a2)

array([False, True, False, True])