In [1]:
import numpy as np

# **Remodelage de tableau NumPy**

In [3]:
arr = np.arange(1, 10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## _3x3_

In [5]:
arr.reshape(3,3)

array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])

# _9x1_

In [7]:
arr.reshape(9,1)

array([[1],
 [2],
 [3],
 [4],
 [5],
 [6],
 [7],
 [8],
 [9]])

## _Remodeler un tableau de 20 éléments_

In [9]:
arr1 = np.arange(1, 21)
arr1

array([ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17,
 18, 19, 20])

In [10]:
arr1.reshape(4,5)

array([[ 1, 2, 3, 4, 5],
 [ 6, 7, 8, 9, 10],
 [11, 12, 13, 14, 15],
 [16, 17, 18, 19, 20]])

In [11]:
arr1.reshape(5,4)

array([[ 1, 2, 3, 4],
 [ 5, 6, 7, 8],
 [ 9, 10, 11, 12],
 [13, 14, 15, 16],
 [17, 18, 19, 20]])

## _2 tableau de 2 lignes et cinq colonnes_

In [13]:
arr1.reshape(2,5,2) # 2 lignes, 5 cols, 2 tableaux

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])