In [1]:
import numpy as np

Chaque dimension a un terme. Le scalaire, le vecteur, la matrice et le tenseur.
* 0D – Scalar
* 1D – Vector
* 2D – Matrix
* 3D ou plus – Tensor

In [2]:
# Le scalarie (aucune dimension)
d0 = np.array(6)
d0, d0.ndim

(array(6), 0)

☝️ dimension 0 ; c'est un scalaire

In [3]:
# Le vecteur (une dimension)
d1 = np.array([1, 2, 3, 4])
d1, d1.ndim

(array([1, 2, 3, 4]), 1)

☝️ Une dimension ; c'est un vecteur  
   C'est comme une colonne sans ligne

In [4]:
# La matrice (en 2D)
d2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8]])
d2, d2.ndim

(array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 2)

☝️ C'est une matrice ; 2  
Il y a des lignes eet colonnes  
Les features ont plusieurs colonnes et lignes comme une matrice  
Les labels n’ont qu’une seule colonne comme un vecteur

Les tenseurs

In [5]:
# Le tenseur en 3D
d3 = np.array([[[1, 2, 3],
                [4, 5, 6]],
               [[7, 8, 9],
                [10, 11, 12]]])
d3, d3.ndim

(array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]]),
 3)

In [6]:
# Les tenseurs en 4D
d4 = np.array([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]],
               [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]])
d4, d4.ndim

(array([[[[ 1,  2],
          [ 3,  4]],
 
         [[ 5,  6],
          [ 7,  8]]],
 
 
        [[[ 9, 10],
          [11, 12]],
 
         [[13, 14],
          [15, 16]]]]),
 4)

## Les types de données et leurs dimensions
* Tableaux · · · · · · · · · · · · · · · · · · · · · · ▶ matrices 2D
* Séries temporelles ou séquences · · ▶ tenseurs 3D
* Images · · · · · · · · · · · · · · · · · · · · · · · ·▶ tenseurs 4D
* Vidéogrammes · · · · · · · · · · · · · · · · · ▶ tenseurs 5D