In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Prendre la ligne 4 à 8

In [3]:
arr[4: 8]

array([4, 5, 6, 7])

## À l’intérieur des crochets, spécifier : [start : stop : step]

In [4]:
arr[1: 10: 2]

array([1, 3, 5, 7, 9])

# Découpage en tableau 2D

In [5]:
np.random.seed(67)
arr1 = np.random.randint(1, 10, (3, 4))
arr1

array([[4, 6, 6, 8],
 [4, 7, 4, 8],
 [9, 6, 4, 7]])

In [6]:
arr1[1:2]

array([[4, 7, 4, 8]])

## Les 2 premières lignes et les 2 du milieu

In [7]:
arr1[0:2, 1:3]

array([[6, 6],
 [7, 4]])

In [8]:
arr1[-3:, 1:-1]

array([[6, 6],
 [7, 4],
 [6, 4]])

☝️ `[-3 :]` Toutes les lignes à partir de -3 seront récupérées.

[1 : -1] utilisation à la fois l’indexation normale et l’indexation inversée. Nous commençons par le premier index jusqu’au dernier qui est -1.

# **Découpage de tableau 3D**

In [9]:
arr2 = np.random.randint(1, 10, (2, 3, 4))
arr2

array([[[5, 8, 2, 4],
        [8, 9, 8, 3],
        [6, 6, 4, 3]],

       [[7, 7, 5, 9],
        [4, 2, 5, 9],
        [3, 8, 1, 8]]])

## _Extraire une "matrice" (plan 2D) complète_

In [10]:
arr2[0, :, :]

array([[5, 8, 2, 4],
 [8, 9, 8, 3],
 [6, 6, 4, 3]])

## _Extraire la ligne 2 du plan 2_

In [11]:
arr2[1, 1, :]

array([4, 2, 5, 9])

In [12]:
arr2[1, 1]

array([4, 2, 5, 9])

## _La troisième colonne_

In [13]:
arr2[1:, 1:, 2]

array([[5, 1]])

## _Extraire un sous-tableau (sous-cube)_

_Sur le premier plan, extraire les deux premières lignes et trois premières colonnes_

In [14]:
arr2[0, 0:2, 0:3]

array([[5, 8, 2],
 [8, 9, 8]])

## _Extraire la même colonne de toutes les lignes et de tous les plans_
_Quatrième colonne dans tout le cube :_

In [15]:
arr2[:, :, 3]

array([[4, 3, 3],
 [9, 9, 8]])

## _Prendre un "slice" sur l’axe des plans (premier axe)_
_Ne prendre que le deuxième plan_

In [16]:
arr2[1]

array([[7, 7, 5, 9],
 [4, 2, 5, 9],
 [3, 8, 1, 8]])

Résumé des syntaxes courantes pour un tableau 3D avec NumPy :
arr2[i, :, :] : ith plan complet

arr2[:, j, :] : jth ligne de chaque plan

arr2[:, :, k] : kth colonne sur tous les plans et lignes

arr2[a:b, c:d, e:f] : sous-cube défini par tranches sur chaque axe